name: Test Checkout

on: [push, workflow_dispatch]

jobs:
  verifica-file:
    runs-on: ubuntu-latest
    steps:
      # PASSO 1: Scarichiamo il codice
      - name: Scarico il codice (Checkout)
        uses: actions/checkout@v4

      # PASSO 2: Verifichiamo che ci sia
      - name: Lista dei file
        run: |
          echo "Ecco cosa ho trovato nella cartella:"
          ls -R